---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-ui-customization
  namespace: acm-policies
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: environment
          operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-policy-ui-customization
placementRef:
  name: placement-policy-ui-customization
  kind: Placement
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: ui-customization
    kind: PolicySet
    apiGroup: policy.open-cluster-management.io
