apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: gitops-policy-generator
policyDefaults:
  namespace: acm-policies
  remediationAction: enforce
placementBindingDefaults:
  name: "binding-policy-gitops"
policies:
  # - name: policy-sealed-secrets-operator
  #   remediationAction: enforce
  #   manifests:
  #     - path: manifests/sealed-secret-operator/overlays/default
  - name: policy-gitops-subscription
    remediationAction: enforce
    manifests:
      - path: manifests/openshift-gitops-operator/operator/overlays/gitops-1.10
  - name: policy-gitops-instance
    manifests:
      - path: manifests/openshift-gitops-operator/instance/overlays/default
  - name: policy-gitops-bootstrap
    manifests:
      - path: manifests/openshift-gitops-bootstrap/overlays/default/
policySets:
  - name: "gitops"
    description: "Policy for bootstrapping cluster with gitops"
    policies:
      # - policy-sealed-secrets-operator
      - policy-gitops-subscription
      - policy-gitops-instance
      - policy-gitops-bootstrap
    generatePolicySetPlacement: false
    placement:
      name: placement-policy-gitops
