apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: patch-enable-policy-generator.yaml
    target:
      kind: ArgoCD

images:
  - name: registry.redhat.io/rhacm2/multicluster-operators-subscription-rhel8
    newTag: v2.8
