apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-ui-customization
spec:
  clusterSets:
    - global
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-ui-customization
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: placement-policy-ui-customization
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: PolicySet
  name: ui-customization
  