apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: openshift-gitops
spec:
  rbac:
    policy: |-
      g, system:cluster-admins, role:admin
      g, IT-Compute-RHO-Super-Admins, role:admin
